(define (problem testing)
    (:domain baba)

    (:objects
    L_00 L_01 L_02 L_03 L_04 L_05 L_10 L_11 L_12 L_13 L_14 L_15 L_20 L_21 L_22 L_23 L_24 L_25 L_30 L_31 L_32 L_33 L_34 L_35 L_40 L_41 L_42 L_43 L_44 L_45 L_50 L_51 L_52 L_53 L_54 L_55 - location
    x1 x2 x3 x4 - sprite
    is1 is2 is3 is4 is5 - is
    y1 - you
    p1 - push
    s1 - stop
    g1 - win
    b1 - baba
    r1 r2 r3 - rock
    w1 w2 w3 - wall
    f1 - flag
    )

    (:init
        ; grid initialization
        (right_connected L_00 L_01 )
        (right_connected L_01 L_02 )
        (right_connected L_02 L_03 )
        (right_connected L_03 L_04 )
        (right_connected L_04 L_05 )
        (right_connected L_10 L_11 )
        (right_connected L_11 L_12 )
        (right_connected L_12 L_13 )
        (right_connected L_13 L_14 )
        (right_connected L_14 L_15 )
        (right_connected L_20 L_21 )
        (right_connected L_21 L_22 )
        (right_connected L_22 L_23 )
        (right_connected L_23 L_24 )
        (right_connected L_24 L_25 )
        (right_connected L_30 L_31 )
        (right_connected L_31 L_32 )
        (right_connected L_32 L_33 )
        (right_connected L_33 L_34 )
        (right_connected L_34 L_35 )
        (right_connected L_40 L_41 )
        (right_connected L_41 L_42 )
        (right_connected L_42 L_43 )
        (right_connected L_43 L_44 )
        (right_connected L_44 L_45 )
        (right_connected L_50 L_51 )
        (right_connected L_51 L_52 )
        (right_connected L_52 L_53 )
        (right_connected L_53 L_54 )
        (right_connected L_54 L_55 )

        (left_connected L_05 L_04 )
        (left_connected L_04 L_03 )
        (left_connected L_03 L_02 )
        (left_connected L_02 L_01 )
        (left_connected L_01 L_00 )
        (left_connected L_15 L_14 )
        (left_connected L_14 L_13 )
        (left_connected L_13 L_12 )
        (left_connected L_12 L_11 )
        (left_connected L_11 L_10 )
        (left_connected L_25 L_24 )
        (left_connected L_24 L_23 )
        (left_connected L_23 L_22 )
        (left_connected L_22 L_21 )
        (left_connected L_21 L_20 )
        (left_connected L_35 L_34 )
        (left_connected L_34 L_33 )
        (left_connected L_33 L_32 )
        (left_connected L_32 L_31 )
        (left_connected L_31 L_30 )
        (left_connected L_45 L_44 )
        (left_connected L_44 L_43 )
        (left_connected L_43 L_42 )
        (left_connected L_42 L_41 )
        (left_connected L_41 L_40 )
        (left_connected L_55 L_54 )
        (left_connected L_54 L_53 )
        (left_connected L_53 L_52 )
        (left_connected L_52 L_51 )
        (left_connected L_51 L_50 )

        (up_connected L_50 L_40 )
        (up_connected L_40 L_30 )
        (up_connected L_30 L_20 )
        (up_connected L_20 L_10 )
        (up_connected L_10 L_00 )
        (up_connected L_51 L_41 )
        (up_connected L_41 L_31 )
        (up_connected L_31 L_21 )
        (up_connected L_21 L_11 )
        (up_connected L_11 L_01 )
        (up_connected L_52 L_42 )
        (up_connected L_42 L_32 )
        (up_connected L_32 L_22 )
        (up_connected L_22 L_12 )
        (up_connected L_12 L_02 )
        (up_connected L_53 L_43 )
        (up_connected L_43 L_33 )
        (up_connected L_33 L_23 )
        (up_connected L_23 L_13 )
        (up_connected L_13 L_03 )
        (up_connected L_54 L_44 )
        (up_connected L_44 L_34 )
        (up_connected L_34 L_24 )
        (up_connected L_24 L_14 )
        (up_connected L_14 L_04 )
        (up_connected L_55 L_45 )
        (up_connected L_45 L_35 )
        (up_connected L_35 L_25 )
        (up_connected L_25 L_15 )
        (up_connected L_15 L_05 )

        (down_connected L_00 L_10 )
        (down_connected L_10 L_20 )
        (down_connected L_20 L_30 )
        (down_connected L_30 L_40 )
        (down_connected L_40 L_50 )
        (down_connected L_01 L_11 )
        (down_connected L_11 L_21 )
        (down_connected L_21 L_31 )
        (down_connected L_31 L_41 )
        (down_connected L_41 L_51 )
        (down_connected L_02 L_12 )
        (down_connected L_12 L_22 )
        (down_connected L_22 L_32 )
        (down_connected L_32 L_42 )
        (down_connected L_42 L_52 )
        (down_connected L_03 L_13 )
        (down_connected L_13 L_23 )
        (down_connected L_23 L_33 )
        (down_connected L_33 L_43 )
        (down_connected L_43 L_53 )
        (down_connected L_04 L_14 )
        (down_connected L_14 L_24 )
        (down_connected L_24 L_34 )
        (down_connected L_34 L_44 )
        (down_connected L_44 L_54 )
        (down_connected L_05 L_15 )
        (down_connected L_15 L_25 )
        (down_connected L_25 L_35 )
        (down_connected L_35 L_45 )
        (down_connected L_45 L_55 )

        (right_edge L_05 )
        (right_edge L_15 )
        (right_edge L_25 )
        (right_edge L_35 )
        (right_edge L_45 )
        (right_edge L_55 )

        (left_edge L_00 )
        (left_edge L_10 )
        (left_edge L_20 )
        (left_edge L_30 )
        (left_edge L_40 )
        (left_edge L_50 )

        (up_edge L_00 )
        (up_edge L_01 )
        (up_edge L_02 )
        (up_edge L_03 )
        (up_edge L_04 )
        (up_edge L_05 )

        (down_edge L_50 )
        (down_edge L_51 )
        (down_edge L_52 )
        (down_edge L_53 )
        (down_edge L_54 )
        (down_edge L_55 )

        (is_operator is1)
        (is_operator is2)
        (is_operator is3)
        (is_operator is4)
        (is_operator is5)

        (is_noun b1)
        (is_noun r1)
        (is_noun r2)
        (is_noun r3)
        (is_noun w1)
        (is_noun w2)
        (is_noun w3)
        (is_noun f1)

        (is_property y1)
        (is_property p1)
        (is_property s1)
        (is_property g1)

        (is_same r1 r2)
        (is_same r2 r1)
        (is_same r1 r3)
        (is_same r3 r1)
        (is_same r2 r3)
        (is_same r3 r2)

        (is_same w1 w2)
        (is_same w2 w1)
        (is_same w1 w3)
        (is_same w3 w1)
        (is_same w2 w3)
        (is_same w3 w2)

        (is_at x1 L_00)
        (has_noun x1 b1)

        (is_at x2 L_01)
        (has_noun x2 r1)

        (is_at x3 L_02)
        (has_noun x3 w1)

        (is_at x4 L_03)
        (has_noun x4 r2)

        (is_at is5 L_20)
        (is_at is1 L_21)
        (is_at r2 L_22)

        (is_at w1 L_23)
        (is_at is2 L_33)
        (is_at w2 L_43)

        (is_at r3 L_40)
        (is_at is3 L_41)
        (is_at w3 L_42)

        (is_at b1 L_25)
        (is_at is4 L_35)
        (is_at y1 L_45)

        (start)

    )


    (:goal
        ; one for each step in the process
        (and
            ;(text_moved)
            ;(properties_removed)
            ;(is_itself_checked)
            ;(nouns_need_change)
            (nouns_changed)
            ;(rules_updated)
            ;(temp_check)
            ;(sentences_checked)
            
            
        )
    )
)