(define (problem testing)
    (:domain baba)

    (:objects

    )

    (:init
        ; grid initialization
        (connected L_00 L_01 right)
        (connected L_01 L_02 right)
        (connected L_02 L_03 right)
        (connected L_03 L_04 right)
        (connected L_04 L_05 right)
        (connected L_10 L_11 right)
        (connected L_11 L_12 right)
        (connected L_12 L_13 right)
        (connected L_13 L_14 right)
        (connected L_14 L_15 right)
        (connected L_20 L_21 right)
        (connected L_21 L_22 right)
        (connected L_22 L_23 right)
        (connected L_23 L_24 right)
        (connected L_24 L_25 right)
        (connected L_30 L_31 right)
        (connected L_31 L_32 right)
        (connected L_32 L_33 right)
        (connected L_33 L_34 right)
        (connected L_34 L_35 right)
        (connected L_40 L_41 right)
        (connected L_41 L_42 right)
        (connected L_42 L_43 right)
        (connected L_43 L_44 right)
        (connected L_44 L_45 right)
        (connected L_50 L_51 right)
        (connected L_51 L_52 right)
        (connected L_52 L_53 right)
        (connected L_53 L_54 right)
        (connected L_54 L_55 right)

        (connected L_05 L_04 left)
        (connected L_04 L_03 left)
        (connected L_03 L_02 left)
        (connected L_02 L_01 left)
        (connected L_01 L_00 left)
        (connected L_15 L_14 left)
        (connected L_14 L_13 left)
        (connected L_13 L_12 left)
        (connected L_12 L_11 left)
        (connected L_11 L_10 left)
        (connected L_25 L_24 left)
        (connected L_24 L_23 left)
        (connected L_23 L_22 left)
        (connected L_22 L_21 left)
        (connected L_21 L_20 left)
        (connected L_35 L_34 left)
        (connected L_34 L_33 left)
        (connected L_33 L_32 left)
        (connected L_32 L_31 left)
        (connected L_31 L_30 left)
        (connected L_45 L_44 left)
        (connected L_44 L_43 left)
        (connected L_43 L_42 left)
        (connected L_42 L_41 left)
        (connected L_41 L_40 left)
        (connected L_55 L_54 left)
        (connected L_54 L_53 left)
        (connected L_53 L_52 left)
        (connected L_52 L_51 left)
        (connected L_51 L_50 left)

        (connected L_50 L_40 up)
        (connected L_40 L_30 up)
        (connected L_30 L_20 up)
        (connected L_20 L_10 up)
        (connected L_10 L_00 up)
        (connected L_51 L_41 up)
        (connected L_41 L_31 up)
        (connected L_31 L_21 up)
        (connected L_21 L_11 up)
        (connected L_11 L_01 up)
        (connected L_52 L_42 up)
        (connected L_42 L_32 up)
        (connected L_32 L_22 up)
        (connected L_22 L_12 up)
        (connected L_12 L_02 up)
        (connected L_53 L_43 up)
        (connected L_43 L_33 up)
        (connected L_33 L_23 up)
        (connected L_23 L_13 up)
        (connected L_13 L_03 up)
        (connected L_54 L_44 up)
        (connected L_44 L_34 up)
        (connected L_34 L_24 up)
        (connected L_24 L_14 up)
        (connected L_14 L_04 up)
        (connected L_55 L_45 up)
        (connected L_45 L_35 up)
        (connected L_35 L_25 up)
        (connected L_25 L_15 up)
        (connected L_15 L_05 up)

        (connected L_00 L_10 down)
        (connected L_10 L_20 down)
        (connected L_20 L_30 down)
        (connected L_30 L_40 down)
        (connected L_40 L_50 down)
        (connected L_01 L_11 down)
        (connected L_11 L_21 down)
        (connected L_21 L_31 down)
        (connected L_31 L_41 down)
        (connected L_41 L_51 down)
        (connected L_02 L_12 down)
        (connected L_12 L_22 down)
        (connected L_22 L_32 down)
        (connected L_32 L_42 down)
        (connected L_42 L_52 down)
        (connected L_03 L_13 down)
        (connected L_13 L_23 down)
        (connected L_23 L_33 down)
        (connected L_33 L_43 down)
        (connected L_43 L_53 down)
        (connected L_04 L_14 down)
        (connected L_14 L_24 down)
        (connected L_24 L_34 down)
        (connected L_34 L_44 down)
        (connected L_44 L_54 down)
        (connected L_05 L_15 down)
        (connected L_15 L_25 down)
        (connected L_25 L_35 down)
        (connected L_35 L_45 down)
        (connected L_45 L_55 down)

        (edge L_05 right)
        (edge L_15 right)
        (edge L_25 right)
        (edge L_35 right)
        (edge L_45 right)
        (edge L_55 right)

        (edge L_00 left)
        (edge L_10 left)
        (edge L_20 left)
        (edge L_30 left)
        (edge L_40 left)
        (edge L_50 left)

        (edge L_00 up)
        (edge L_01 up)
        (edge L_02 up)
        (edge L_03 up)
        (edge L_04 up)
        (edge L_05 up)

        (edge L_50 down)
        (edge L_51 down)
        (edge L_52 down)
        (edge L_53 down)
        (edge L_54 down)
        (edge L_55 down)

        (is_text is1)
        (is_text is2)
        ;(is_text is3)
        (is_text b1)
        (is_text f1)
        ;(is_text r1)
        ;(is_text w1)
        ;(is_text p1)
        (is_text y1)
        (is_text g1)
        ;(is_text s1)

        (has_property is1 push_const)
        (has_property is2 push_const)
        (has_property b1 push_const)
        (has_property f1 push_const)
        (has_property y1 push_const)
        (has_property g1 push_const)

        (is_operator is1)
        (is_operator is2)
        ;(is_operator is3)

        (is_noun b1)
        ;(is_noun r1)
        ;(is_noun w1)
        (is_noun f1)

        (is_property y1)
        ;(is_property p1)
        ;(is_property s1)
        (is_property g1)

        (is_same win_const g1)
        (is_same g1 win_const)

        (is_same you_const y1)
        (is_same y1 you_const)

        ; (is_same push_const p1)
        ; (is_same p1 push_const)

        ; (is_same stop_const s1)
        ; (is_same s1 stop_const)

        (is_at x1 L_00)
        (has_noun x1 b1)

        (is_at x2 L_03)
        (has_noun x2 f1)

        ; (is_at x3 L_02)
        ; (has_noun x3 w1)

        ; (is_at x4 L_13)
        ; (has_noun x4 r1)

        (is_at f1 L_21)
        (is_at is1 L_23)
        (is_at g1 L_25)

        ; (is_at w1 L_23)
        ; (is_at is2 L_33)
        ; (is_at s1 L_43)

        (is_at b1 L_50)
        (is_at is2 L_51)
        (is_at y1 L_52)

        (text_moved)

    )


    (:goal
        ; one for each step in the process
        (and
            ;(players_moved)
            ;(text_moved)
            ;(properties_removed)
            ;(sentences_checked)
            ;(nouns_need_change)
            ;(nouns_changed)
            ;(properties_given)
            ;(moveable_given)
            ;(spreading)
            ;(choose_move)
            
            ;(is_at x1 L_21)
            ;(is_at f1 L_22)
            ;(chosen_dir right)

            ;(temp_check)
            (level-complete)

        )
    )
)